# keras jypyter builds on base keras image
FROM lab41/keras-cuda
MAINTAINER Kyle F <kylef@lab41.org>


# install jupyter
RUN pip install jupyter
RUN cd /tmp && \
    git clone https://github.com/ipython-contrib/IPython-notebook-extensions.git && \
    cd IPython-notebook-extensions && \
    mkdir --parents /root/.local/share/jupyter && \
    python setup.py install


# create ipython profile
RUN ipython profile create nbserver


# setup git preferences
ENV GIT_REMOTE_URL 'git@github.com:gitbot41/sunny-side-up.git'
ENV GIT_REPO_UPSTREAM 'Lab41/sunny-side-up'
ENV GIT_USER "gitbot41"
ENV GIT_EMAIL "gitbot41@gmail.com"


# install extensions
ADD config/jupyter/extensions/notebook.json /root/.jupyter/nbconfig/
ADD config/jupyter/extensions/github-commit-push.js /root/.ipython/nbextensions/
ADD config/jupyter/extensions/github_commit_push.py /root/.local/share/jupyter/extensions/


# configure git access
ADD config/ssh /root/.ssh
RUN pip install gitpython && \
    git config --global user.name  $GIT_USER && \
    git config --global user.email $GIT_EMAIL && \
    chmod 0400 /root/.ssh/id_rsa
RUN sed -i "s|git_url = .*$|git_url = '$GIT_REMOTE_URL'|g" /root/.local/share/jupyter/extensions/github_commit_push.py && \
    sed -i "s|git_user = .*$|git_user = '$GIT_USER'|g" /root/.local/share/jupyter/extensions/github_commit_push.py && \
    sed -i "s|git_repo_upstream = .*$|git_repo_upstream = '$GIT_REPO_UPSTREAM'|g" /root/.local/share/jupyter/extensions/github_commit_push.py


# add git filter to strip notebook output
RUN wget -O /usr/local/bin/ipynb_stripout "https://raw.githubusercontent.com/jond3k/ipynb_stripout/master/ipynb_stripout" && \
    chmod +x /usr/local/bin/ipynb_stripout && \
    git config --global filter.ipynb_stripout.clean ipynb_stripout && \
    git config --global filter.ipynb_stripout.smudge cat && \
    git config --global filter.ipynb_stripout.required true


# default to jupyter notebook
ADD config/jupyter/run/notebook.sh /notebook.sh
CMD ["/notebook.sh"]
